// ひらがな復習アプリで使用する46文字の確定データ。
// 文字・単語・読み上げフレーズ・画像パスは、このファイルを唯一の正とする。

export const HIRAGANA_DATA = [
  { id: 1, character: "あ", word: "あひる", phrase: "あひるのあ", image: "assets/images/hiragana/01_a_ahiru.webp", difficult: true },
  { id: 2, character: "い", word: "いす", phrase: "いすのい", image: "assets/images/hiragana/02_i_isu.webp", difficult: false },
  { id: 3, character: "う", word: "うさぎ", phrase: "うさぎのう", image: "assets/images/hiragana/03_u_usagi.webp", difficult: false },
  { id: 4, character: "え", word: "えんぴつ", phrase: "えんぴつのえ", image: "assets/images/hiragana/04_e_enpitsu.webp", difficult: false },
  { id: 5, character: "お", word: "おにぎり", phrase: "おにぎりのお", image: "assets/images/hiragana/05_o_onigiri.webp", difficult: false },
  { id: 6, character: "か", word: "かさ", phrase: "かさのか", image: "assets/images/hiragana/06_ka_kasa.webp", difficult: false },
  { id: 7, character: "き", word: "きりん", phrase: "きりんのき", image: "assets/images/hiragana/07_ki_kirin.webp", difficult: true },
  { id: 8, character: "く", word: "くつ", phrase: "くつのく", image: "assets/images/hiragana/08_ku_kutsu.webp", difficult: false },
  { id: 9, character: "け", word: "けむし", phrase: "けむしのけ", image: "assets/images/hiragana/09_ke_kemushi.webp", difficult: false },
  { id: 10, character: "こ", word: "こあら", phrase: "こあらのこ", image: "assets/images/hiragana/10_ko_koala.webp", difficult: false },
  { id: 11, character: "さ", word: "さかな", phrase: "さかなのさ", image: "assets/images/hiragana/11_sa_sakana.webp", difficult: true },
  { id: 12, character: "し", word: "しまうま", phrase: "しまうまのし", image: "assets/images/hiragana/12_shi_shimauma.webp", difficult: false },
  { id: 13, character: "す", word: "すべりだい", phrase: "すべりだいのす", image: "assets/images/hiragana/13_su_suberidai.webp", difficult: false },
  { id: 14, character: "せ", word: "せっけん", phrase: "せっけんのせ", image: "assets/images/hiragana/14_se_sekken.webp", difficult: false },
  { id: 15, character: "そ", word: "そら", phrase: "そらのそ", image: "assets/images/hiragana/15_so_sora.webp", difficult: false },
  { id: 16, character: "た", word: "たまご", phrase: "たまごのた", image: "assets/images/hiragana/16_ta_tamago.webp", difficult: false },
  { id: 17, character: "ち", word: "ちゅーりっぷ", phrase: "ちゅーりっぷのち", image: "assets/images/hiragana/17_chi_churippu.webp", difficult: false },
  { id: 18, character: "つ", word: "つみき", phrase: "つみきのつ", image: "assets/images/hiragana/18_tsu_tsumiki.webp", difficult: false },
  { id: 19, character: "て", word: "てぶくろ", phrase: "てぶくろのて", image: "assets/images/hiragana/19_te_tebukuro.webp", difficult: false },
  { id: 20, character: "と", word: "とけい", phrase: "とけいのと", image: "assets/images/hiragana/20_to_tokei.webp", difficult: false },
  { id: 21, character: "な", word: "ながぐつ", phrase: "ながぐつのな", image: "assets/images/hiragana/21_na_nagagutsu.webp", difficult: false },
  { id: 22, character: "に", word: "にわとり", phrase: "にわとりのに", image: "assets/images/hiragana/22_ni_niwatori.webp", difficult: false },
  { id: 23, character: "ぬ", word: "ぬいぐるみ", phrase: "ぬいぐるみのぬ", image: "assets/images/hiragana/23_nu_nuigurumi.webp", difficult: true },
  { id: 24, character: "ね", word: "ねこ", phrase: "ねこのね", image: "assets/images/hiragana/24_ne_neko.webp", difficult: true },
  { id: 25, character: "の", word: "きのこ", phrase: "きのこのの", image: "assets/images/hiragana/25_no_kinoko.webp", difficult: true },
  { id: 26, character: "は", word: "はち", phrase: "はちのは", image: "assets/images/hiragana/26_ha_hachi.webp", difficult: true },
  { id: 27, character: "ひ", word: "ひこうき", phrase: "ひこうきのひ", image: "assets/images/hiragana/27_hi_hikouki.webp", difficult: false },
  { id: 28, character: "ふ", word: "ふうせん", phrase: "ふうせんのふ", image: "assets/images/hiragana/28_fu_fuusen.webp", difficult: false },
  { id: 29, character: "へ", word: "へりこぷたー", phrase: "へりこぷたーのへ", image: "assets/images/hiragana/29_he_herikoputa.webp", difficult: false },
  { id: 30, character: "ほ", word: "ほし", phrase: "ほしのほ", image: "assets/images/hiragana/30_ho_hoshi.webp", difficult: true },
  { id: 31, character: "ま", word: "まど", phrase: "まどのま", image: "assets/images/hiragana/31_ma_mado.webp", difficult: false },
  { id: 32, character: "み", word: "みず", phrase: "みずのみ", image: "assets/images/hiragana/32_mi_mizu.webp", difficult: false },
  { id: 33, character: "む", word: "かたつむり", phrase: "かたつむりのむ", image: "assets/images/hiragana/33_mu_katatsumuri.webp", difficult: true },
  { id: 34, character: "め", word: "めがね", phrase: "めがねのめ", image: "assets/images/hiragana/34_me_megane.webp", difficult: true },
  { id: 35, character: "も", word: "もも", phrase: "もものも", image: "assets/images/hiragana/35_mo_momo.webp", difficult: false },
  { id: 36, character: "や", word: "やね", phrase: "やねのや", image: "assets/images/hiragana/36_ya_yane.webp", difficult: false },
  { id: 37, character: "ゆ", word: "ゆきだるま", phrase: "ゆきだるまのゆ", image: "assets/images/hiragana/37_yu_yukidaruma.webp", difficult: true },
  { id: 38, character: "よ", word: "よっと", phrase: "よっとのよ", image: "assets/images/hiragana/38_yo_yotto.webp", difficult: false },
  { id: 39, character: "ら", word: "らいおん", phrase: "らいおんのら", image: "assets/images/hiragana/39_ra_raion.webp", difficult: false },
  { id: 40, character: "り", word: "りんご", phrase: "りんごのり", image: "assets/images/hiragana/40_ri_ringo.webp", difficult: false },
  { id: 41, character: "る", word: "かえる", phrase: "かえるのる", image: "assets/images/hiragana/41_ru_kaeru.webp", difficult: false },
  { id: 42, character: "れ", word: "れもん", phrase: "れもんのれ", image: "assets/images/hiragana/42_re_remon.webp", difficult: false },
  { id: 43, character: "ろ", word: "ろぼっと", phrase: "ろぼっとのろ", image: "assets/images/hiragana/43_ro_robotto.webp", difficult: false },
  { id: 44, character: "わ", word: "わに", phrase: "わにのわ", image: "assets/images/hiragana/44_wa_wani.webp", difficult: false },
  { id: 45, character: "を", word: "ほんをよむ", phrase: "ほんをよむのを", image: "assets/images/hiragana/45_wo_honwoyomu.webp", difficult: true },
  { id: 46, character: "ん", word: "ぶらんこ", phrase: "ぶらんこのん", image: "assets/images/hiragana/46_n_buranko.webp", difficult: false },
];

